# Funding sources for APRSdroid 9M2PJU Mod
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

custom: ["https://buymeacoffee.com/9m2pju", "https://wise.com/pay/me/faizulz13"]
